// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.18.0
// source: mygrpc.proto

package mygrpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LastNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	First string `protobuf:"bytes,1,opt,name=first,proto3" json:"first,omitempty"`
}

func (x *LastNameRequest) Reset() {
	*x = LastNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mygrpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LastNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastNameRequest) ProtoMessage() {}

func (x *LastNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mygrpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastNameRequest.ProtoReflect.Descriptor instead.
func (*LastNameRequest) Descriptor() ([]byte, []int) {
	return file_mygrpc_proto_rawDescGZIP(), []int{0}
}

func (x *LastNameRequest) GetFirst() string {
	if x != nil {
		return x.First
	}
	return ""
}

type LastNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Last string `protobuf:"bytes,1,opt,name=last,proto3" json:"last,omitempty"`
	Err  string `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *LastNameResponse) Reset() {
	*x = LastNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mygrpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LastNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastNameResponse) ProtoMessage() {}

func (x *LastNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mygrpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastNameResponse.ProtoReflect.Descriptor instead.
func (*LastNameResponse) Descriptor() ([]byte, []int) {
	return file_mygrpc_proto_rawDescGZIP(), []int{1}
}

func (x *LastNameResponse) GetLast() string {
	if x != nil {
		return x.Last
	}
	return ""
}

func (x *LastNameResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_mygrpc_proto protoreflect.FileDescriptor

var file_mygrpc_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x79, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0x27, 0x0a, 0x0f, 0x4c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x72, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x72, 0x73, 0x74, 0x22, 0x38, 0x0a, 0x10, 0x4c,
	0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6c, 0x61, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c,
	0x61, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x65, 0x72, 0x72, 0x32, 0x41, 0x0a, 0x06, 0x4d, 0x79, 0x47, 0x72, 0x70, 0x63, 0x12,
	0x37, 0x0a, 0x08, 0x4c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x13, 0x2e, 0x70, 0x62,
	0x2e, 0x4c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x6d, 0x79,
	0x67, 0x72, 0x70, 0x63, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mygrpc_proto_rawDescOnce sync.Once
	file_mygrpc_proto_rawDescData = file_mygrpc_proto_rawDesc
)

func file_mygrpc_proto_rawDescGZIP() []byte {
	file_mygrpc_proto_rawDescOnce.Do(func() {
		file_mygrpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_mygrpc_proto_rawDescData)
	})
	return file_mygrpc_proto_rawDescData
}

var file_mygrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mygrpc_proto_goTypes = []interface{}{
	(*LastNameRequest)(nil),  // 0: pb.LastNameRequest
	(*LastNameResponse)(nil), // 1: pb.LastNameResponse
}
var file_mygrpc_proto_depIdxs = []int32{
	0, // 0: pb.MyGrpc.LastName:input_type -> pb.LastNameRequest
	1, // 1: pb.MyGrpc.LastName:output_type -> pb.LastNameResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mygrpc_proto_init() }
func file_mygrpc_proto_init() {
	if File_mygrpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mygrpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LastNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mygrpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LastNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mygrpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mygrpc_proto_goTypes,
		DependencyIndexes: file_mygrpc_proto_depIdxs,
		MessageInfos:      file_mygrpc_proto_msgTypes,
	}.Build()
	File_mygrpc_proto = out.File
	file_mygrpc_proto_rawDesc = nil
	file_mygrpc_proto_goTypes = nil
	file_mygrpc_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MyGrpcClient is the client API for MyGrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MyGrpcClient interface {
	LastName(ctx context.Context, in *LastNameRequest, opts ...grpc.CallOption) (*LastNameResponse, error)
}

type myGrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewMyGrpcClient(cc grpc.ClientConnInterface) MyGrpcClient {
	return &myGrpcClient{cc}
}

func (c *myGrpcClient) LastName(ctx context.Context, in *LastNameRequest, opts ...grpc.CallOption) (*LastNameResponse, error) {
	out := new(LastNameResponse)
	err := c.cc.Invoke(ctx, "/pb.MyGrpc/LastName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyGrpcServer is the server API for MyGrpc service.
type MyGrpcServer interface {
	LastName(context.Context, *LastNameRequest) (*LastNameResponse, error)
}

// UnimplementedMyGrpcServer can be embedded to have forward compatible implementations.
type UnimplementedMyGrpcServer struct {
}

func (*UnimplementedMyGrpcServer) LastName(context.Context, *LastNameRequest) (*LastNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LastName not implemented")
}

func RegisterMyGrpcServer(s *grpc.Server, srv MyGrpcServer) {
	s.RegisterService(&_MyGrpc_serviceDesc, srv)
}

func _MyGrpc_LastName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LastNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyGrpcServer).LastName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MyGrpc/LastName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyGrpcServer).LastName(ctx, req.(*LastNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MyGrpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.MyGrpc",
	HandlerType: (*MyGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LastName",
			Handler:    _MyGrpc_LastName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mygrpc.proto",
}
